<?php

namespace Xshare\GeneralBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewsSubscriberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsSubscriberRepository extends EntityRepository
{
}