imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    translator:      { fallback: en }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: en
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false
services:
  xshare.twig.extension.debug:
          class:        Twig_Extension_Debug
          tags:
              - { name: 'twig.extension' }
genemu_form:
    captcha: ~

parameters:
    max_categories_on_new_category_page: 10
    max_categories_on_new_product_page: 10
    max_user_products_on_new_product_page: 10
    max_products_on_category_items_page: 10
    pager_block: 5
    max_categories_on_category_list_page: 10
    max_products_on_list_all_products_page: 10
    max_requests_on_page: 10
    max_user_products_on_user_details_page: 2
    max_users_on_users_list_page: 8
    max_polls_per_page : 10
    max_top_products: 8
    max_top_users: 10
    max_top_categories_on_top_categories_page: 10
    max_top_categories: 3
#for my requests page pagination
    max_user_requests_per_page: 10
#if you change this params you need to change the translation to
    not_login_error : "It is necessary to login to access this page!"
    no_access_error : "You do not have the necessary rights to access this page!"
    product_delete_msg : "You have successfully delete product!"
#end erorr params
#Breadcrumb configuration
white_october_breadcrumbs: ~
