XshareGeneralBundle:
    resource: "@XshareGeneralBundle/Controller/"
    type:     annotation
    prefix:   /
    
XsharePollBundle:
    resource: "@XsharePollBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    defaults: { _locale: ro }
    requirements:
        _locale: en|ro

XshareProductBundle:
    resource: "@XshareProductBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    defaults: { _locale: ro }
    requirements:
        _locale: en|ro

XshareUserBundle:
    resource: "@XshareUserBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    defaults: { _locale: ro }
    requirements:
        _locale: en|ro

XshareSecurityBundle:
    resource: "@XshareSecurityBundle/Controller/"
    type:     annotation
    

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
