<?php

namespace Xshare\PollBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PollResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PollResultRepository extends EntityRepository
{ 
}